### ISSUE TITLE
Có thể ddos được 1 server chặn ip nước ngoài không bạn

### ISSUE THREAD

**Issue by ghost** [KhanhNguyen9872/ddos_python3#1]
mình cảm ơn nha

**Comment by KhanhNguyen9872** [comment]
> mình cảm ơn nha

đây chỉ là 1 chương trình ddos thông thường = python3, nó có thể ddos nhưng không mạnh lắm, phải chạy nhiều tab mới mạnh, tool này chỉ khuyến khích bạn test ddos server thôi nhé! còn việc chặn ip = cloudflare xịn thì tớ xin chịu ạ! có 1 số web cloudflare nhưng hàng dởm, ddos port 443 vẫn đc
